set(headers ${headers}
	include/Utils.h
	include/PCH.h
	include/Settings.h
	include/Hooks.h
	include/MCP.h
	include/Input.h
	include/Renderer.h
	include/Logger.h
	include/Service.h
    include/Interaction.h
    include/BoundingBox.hpp
    include/Theme.h
	src/ImGui/Graphics.h
    src/ImGui/Styles.h
    src/ImGui/IconsFonts.h
    include/PapyrusAPI/Bindings.h
    include/PapyrusAPI/Sinks.h
)
