set(sources ${sources}
	src/plugin.cpp
	src/Utils.cpp
	src/Translations.cpp
	src/Settings.cpp
	src/Hooks.cpp
	src/MCP.cpp
 	src/Input.cpp
 	src/Renderer.cpp
 	src/Service.cpp
	include/API/HandshakeRegistry.cpp
 	src/Interaction.cpp
 	src/Tutorial.cpp
 	src/Theme.cpp
	src/ImGui/Graphics.cpp
    src/ImGui/Styles.cpp
    src/ImGui/IconFont.cpp
    src/ImGui/PromptDrawing.cpp
    src/ImGui/PromptLayouts.cpp
    include/PapyrusAPI/Bindings.cpp
    include/PapyrusAPI/Sinks.cpp
)
