set(sources ${sources}
	src/plugin.cpp
	src/Utils.cpp
	src/Settings.cpp
	src/Hooks.cpp
	src/MCP.cpp
 	src/Input.cpp
 	src/Tasker.cpp
 	src/Renderer.cpp
 	src/Service.cpp
 	src/Interaction.cpp
 	src/Geometry.cpp
	src/ImGui/Graphics.cpp
    src/ImGui/Widgets.cpp
    src/ImGui/Util.cpp
    src/ImGui/Styles.cpp
    src/ImGui/IconsFonts.cpp
    src/ImGui/IconsFontAwesome6.cpp
    src/ImGui/FormComboBox.cpp
    include/PapyrusAPI/Bindings.cpp
    include/PapyrusAPI/Sinks.cpp
)
